-- Corrector AI — schéma PostgreSQL/Supabase du pilote
-- À exécuter avec le rôle propriétaire de la base. Les identifiants de copie
-- sont des clés Storage opaques, jamais des URL publiques.

BEGIN;

CREATE TABLE IF NOT EXISTS professors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom TEXT NOT NULL,
    prenom TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professor_id BIGINT NOT NULL REFERENCES professors(id),
    nom TEXT NOT NULL,
    prenom TEXT NOT NULL,
    classe TEXT NOT NULL,
    email TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professor_id BIGINT NOT NULL REFERENCES professors(id),
    matiere TEXT NOT NULL DEFAULT '',
    niveau TEXT NOT NULL DEFAULT '',
    titre TEXT NOT NULL DEFAULT '',
    total_points DOUBLE PRECISION NOT NULL DEFAULT 20 CHECK (total_points > 0),
    exercices_json TEXT NOT NULL DEFAULT '[]',
    pdf_path TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id),
    professor_id BIGINT NOT NULL REFERENCES professors(id),
    subject_id BIGINT REFERENCES subjects(id) ON DELETE SET NULL,
    matiere TEXT NOT NULL,
    niveau TEXT NOT NULL DEFAULT '',
    date_examen DATE NOT NULL DEFAULT CURRENT_DATE,
    note_totale DOUBLE PRECISION NOT NULL DEFAULT 0,
    note_sur DOUBLE PRECISION NOT NULL DEFAULT 20 CHECK (note_sur > 0),
    appreciation TEXT NOT NULL DEFAULT '',
    image_path TEXT NOT NULL DEFAULT '',
    alerte_anomalie INTEGER NOT NULL DEFAULT 0 CHECK (alerte_anomalie IN (0, 1)),
    message_anomalie TEXT NOT NULL DEFAULT '',
    review_status TEXT NOT NULL DEFAULT 'pending_review'
        CHECK (review_status IN ('pending_review', 'needs_revision', 'approved')),
    reviewed_at TIMESTAMPTZ,
    reviewed_by BIGINT REFERENCES professors(id) ON DELETE SET NULL,
    review_comment TEXT NOT NULL DEFAULT '',
    ai_note_totale DOUBLE PRECISION,
    ai_appreciation TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
    numero INTEGER NOT NULL CHECK (numero >= 0),
    enonce TEXT NOT NULL DEFAULT '',
    reponse_eleve TEXT NOT NULL DEFAULT '',
    reponse_attendue TEXT NOT NULL DEFAULT '',
    points_obtenus DOUBLE PRECISION NOT NULL DEFAULT 0,
    points_max DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (points_max >= 0),
    correct INTEGER NOT NULL DEFAULT 0 CHECK (correct IN (0, 1)),
    feedback TEXT NOT NULL DEFAULT '',
    erreurs_types TEXT NOT NULL DEFAULT '',
    UNIQUE (exam_id, numero)
);

CREATE TABLE IF NOT EXISTS review_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
    professor_id BIGINT NOT NULL REFERENCES professors(id),
    action TEXT NOT NULL CHECK (action IN ('approved', 'sent_back_for_revision')),
    previous_status TEXT NOT NULL DEFAULT '',
    new_status TEXT NOT NULL,
    note_before DOUBLE PRECISION,
    note_after DOUBLE PRECISION,
    comment TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS calibration_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL UNIQUE REFERENCES exams(id) ON DELETE CASCADE,
    professor_id BIGINT NOT NULL REFERENCES professors(id),
    reference_note DOUBLE PRECISION NOT NULL,
    reference_note_sur DOUBLE PRECISION NOT NULL DEFAULT 20 CHECK (reference_note_sur > 0),
    reference_source TEXT NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS students_professor_class_name_idx
    ON students (professor_id, classe, nom, prenom);
CREATE INDEX IF NOT EXISTS exams_professor_created_idx
    ON exams (professor_id, created_at DESC);
CREATE INDEX IF NOT EXISTS exams_student_subject_date_idx
    ON exams (student_id, matiere, date_examen DESC);
CREATE INDEX IF NOT EXISTS exams_review_queue_idx
    ON exams (professor_id, review_status, created_at DESC);
CREATE INDEX IF NOT EXISTS review_events_exam_created_idx
    ON review_events (exam_id, created_at ASC);

-- Les accès Data API restent fermés par défaut : le backend utilise une URL
-- PostgreSQL secrète avec le rôle propriétaire. Toute politique publique doit
-- être ajoutée explicitement et soumise à revue de sécurité.
ALTER TABLE professors ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE review_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE calibration_cases ENABLE ROW LEVEL SECURITY;

COMMIT;
